---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/_index.md
  label: Gallery
- type: document
  path: content/contact/_index.md
  label: Contact
- type: directory
  path: content/texts
  label: Texts
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - text
upload_dir: content/images
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
